version: 0.0
os: linux

files:
  - source: /
    destination: /data/home/ubuntu/app
    file_exists_behavior: OVERWRITE

permissions:
  - object: /data/home/ubuntu/app
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: cleanup-after-install.sh
      timeout: 60
      runas: root
