version: 0.0

os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: clean.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: cleanup-after-install.sh
      timeout: 60
      runas: ubuntu